apiVersion: v1
kind: Pod
metadata:
  name: inference-requests-limits
spec:
  containers:
    - name: inference-requests-limits
      image: skrivva/online_inference_image
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80